### ISSUE TITLE
package.json main should reference minified file

### ISSUE THREAD

**Issue by piotrwitek** [goldenyz/react-perfect-scrollbar#1]
please change your package.json main file entry to refer to min bundle file
your non-minified bundle will not work with other module bundlers like jspm, because you are depending internally on some webpack loading features
you can reference non-minified bundle with for example jsnext:main or pkg.module: check here for more details https://github.com/rollup/rollup/wiki/pkg.module

**Comment by goldenyz** [comment]
fixed in the last commit
