### ISSUE TITLE
Scrollbar remains visible until you scroll

### ISSUE THREAD

**Issue by phil-dileo** [goldenyz/react-perfect-scrollbar#10]
`"react-perfect-scrollbar": "0.2.0",`

I'm using this to implement a tbody that scrolls while the table headers stay put.  The problem I'm having is that if the number of rows is large such that overflow is required and then the number of rows decreases, the scrollbar hangs around.  Once you scroll the display gets updated to none.  Wondering why it doesn't update automatically?

**Comment by goldenyz** [comment]
Closed the for PR #11
