### ISSUE TITLE
Auto scroll to end

### ISSUE THREAD

**Issue by NimaKaviyani** [goldenyz/react-perfect-scrollbar#100]
Hi, I want use this component for chat box.
Is it possible to scroll in start be at the end of the page and can I update scroll to end with any event?

**Comment by goldenyz** [comment]
Use [containerRef](https://github.com/goldenyz/react-perfect-scrollbar#containerref) to set the scroll position. Hook the [onYReachEnd](https://github.com/goldenyz/react-perfect-scrollbar#onyreachstart) to get the event of end reached
