### ISSUE TITLE
Remove or disable PerfectScrollbar for mobiles

### ISSUE THREAD

**Issue by kishan143-jaiswal** [goldenyz/react-perfect-scrollbar#101]
`<PerfectScrollbar options={{ suppressScrollX: true, suppressScrollY: false }}>
<mycomponent/>
</PerfectScrollbar>`

**Comment by goldenyz** [comment]
?

**Comment by kishan143-jaiswal** [comment]
i want to neglect perfectscrollbar and use default mobile scroll for mobile devices
is this possible to do ?

**Comment by goldenyz** [comment]
Then why do you want to use this component? just use `div` with `overflow: auto` will meet your requirement

**Comment by kishan143-jaiswal** [comment]
ok let me figure it out , thanks for your response

**Comment by GendelfLugansk** [comment]
If you want to disable PerfectScrollbar on mobile devices, you can use [react-device-detect](https://www.npmjs.com/package/react-device-detect) package to detect mobile device and conditionally use PerfectScrollbar, i.e.

```
import { isMobile } from "react-device-detect";

//...
//Code of component
///...

{isMobile ? (
  <div className={"overflow-y-auto"}>
    <SideNavigation />
  </div>
) : (
  <PerfectScrollbar>
    <SideNavigation />
  </PerfectScrollbar>
)}
```

In this way, PC users will see perfect scrollbar and mobile users will see their native scroll
