### ISSUE TITLE
Warnings scroll-blocking 'touchstart' and 'wheel' event

### ISSUE THREAD

**Issue by robsonkades** [goldenyz/react-perfect-scrollbar#103]
Warnings are displayed in the console.log.

`event-manager.js:12 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

`[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

`event-manager.js:12 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

**Versions**
"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-perfect-scrollbar": "^1.5.8",

Google Chrome
Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by goldenyz** [comment]
Refer to the explanation: https://github.com/mdbootstrap/perfect-scrollbar/issues/560#issuecomment-266291396

**Comment by ChambreNoire** [comment]
> Refer to the explanation: https://github.com/mdbootstrap/perfect-scrollbar/issues/560#issuecomment-266291396

The link doesn't work anymore. I'm having the same problem with React 18...

**Comment by rafahell** [comment]
same here,  I'm having the same problem with React 18...
