### ISSUE TITLE
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>

### ISSUE THREAD

**Issue by acatzk** [goldenyz/react-perfect-scrollbar#133]
When my application resize into mobile and when i try to scroll it using scrollbar it got me this error [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>

HOW CAN I FIX IT?

![image](https://user-images.githubusercontent.com/38458781/108596477-4bf20780-73c0-11eb-90ba-f31488e989c0.png)

**Comment by jeremie-gauthier** [comment]
Hey !

I ran into the same issue and fixed it by adding `style={{ touchAction: "none" }}` to the `ScrollBar` component.

```js
import ScrollBar from "react-perfect-scrollbar";


<ScrollBar style={{ touchAction: "none" }}>
  ...
</ScrollBar>
```

Hope it helps !

**Comment by acatzk** [comment]
> Hey !
> 
> I ran into the same issue and fixed it by adding `style={{ touchAction: "none" }}` to the `ScrollBar` component.
> 
> ```js
> import ScrollBar from "react-perfect-scrollbar";
> 
> 
> <ScrollBar style={{ touchAction: "none" }}>
>   ...
> </ScrollBar>
> ```
> 
> Hope it helps !

Its also works for me.... thank you bro!
