### ISSUE TITLE
Implemented as requested and got this

### ISSUE THREAD

**Issue by s-corley** [goldenyz/react-perfect-scrollbar#16]
![toscrollbar](https://user-images.githubusercontent.com/28542849/28786129-4272fa7e-75e6-11e7-8c00-2d18a93e9493.PNG)

**Comment by goldenyz** [comment]
Could you give me a code snippet about this issue? It seems that you have import an undefined component

**Comment by goldenyz** [comment]
@s-corley Any updates?

**Comment by goldenyz** [comment]
@s-corley I will close this issue. If any updates, you can reopen it at any time.

**Comment by s-corley** [comment]
Hi, Sorry I was away yesterday. I cannot reopen since I didn't close it. 
Here is my code:
```
class DocumentHit extends SearchkitComponent<any, any> {
     ...
  render() {
   ...
    var lobVar = result._source.lob;
    var premVar = result._source.premium;
    var statVar = result._source.status;
    var circVar = result._source.circular;
    var filedVar = result._source.date_filed;
    var effVar = result._source.effective_date;
    var formVar = result._source.form;
    var enteredVar = result._source.date_entered;
    var subVar = result._source.submitted_by;
    var effDate = new Date(effVar);
    var enteredDate = new Date(enteredVar);
    var filedDate = new Date(filedVar);
     ...
    if (lobVar != null && lobVar != '') {
      var thisLob = "" + result._source.lob;

      var newLob = thisLob.replace(/ /g, "\u00a0");
      lobVar = <div className="section">
        <span className="lobHead subHeader">Line of Business: </span> <br />
        <span className={this.props.bemBlocks.item("state")} style={theStyle}>{newLob}<br/>{' '}</span></div>;
    }
    ...
<div className={this.props.bemBlocks.item().mix(this.props.bemBlocks.container("item"))} key={result.files}>
 
        <div id="titles">
          <a className="linking" href={url} target="_blank">Open</a>
          <div className="fileIcon">{imageTag}   
          </div>
          <br />
          <b id="summary" className={this.props.bemBlocks.item("state")}>{result._source.form_title} </b> </div>
        <div id="leftSide">
<PerfectScrollbar>
          {circVar} 
          {productFilVar} 
          {statVar}
          {subjectVar}
          {topVar}
          {this.changeLob(result._source.lob + "")}  
          {profVar} 
          {filedVar}
          {effVar}
          {enteredVar}
          {linkRateVar}
          {subVar}
          {idVar}

</PerfectScrollbar>
        </div>     
              </div>    




    )
  }
}

```


I tried putting the PerfectScrollbar outside of that inner div as well.  When trying to implement PerfectScrollbar nothing inside what should be inside the scrollbar shows. I currently have a normal browser scrollbar. Thanks for the help

**Comment by goldenyz** [comment]
Sorry, I will reopen it.
For this issue, please ensure that:
1. the PerfectScrollbar has been well imported. (You can also add console.log(PerfectScrollbar) in render and see if there are any output);
2. replace the PerfectScrollbar with div to see if the error disappeared.

**Comment by s-corley** [comment]
It has been imported correctly. . the console.log(PerfectScrollbar) returned 'undefined'

**Comment by goldenyz** [comment]
So we need to figure out why is the imported PerfectScrollbar 'undefined'. Could you share the import part of this file?

**Comment by goldenyz** [comment]
@s-corley any updates?

**Comment by jeffcarey** [comment]
I had a similar issue. When I ran console.log(PerfectScrollbar), I got an empty object instead of undefined. I'm currently using requirejs but will be moving to webpack in a few weeks. I'll try again then.

**Comment by hristijankiko** [comment]
Had same issue. It works if you use 'require('react-perfect-scrollbar')'. 

It seems like there is something wrong with the exports of this module as other module imports seem to be working fine. I don't have time to look into this in depth but I hope this helps someone.

**Comment by goldenyz** [comment]
@hristijankiko  Could you provide your webpack and babel config? I will take a look at it

**Comment by pratyushoak** [comment]
I see the same problem as well.

**Comment by goldenyz** [comment]
@pratyushoak could you provide an example project for me to repro?

**Comment by goldenyz** [comment]
I will close this issue for no any updates.
