### ISSUE TITLE
Can you expose getContainer() method to return underlying _container ref?

### ISSUE THREAD

**Issue by pinebit** [goldenyz/react-perfect-scrollbar#19]
I need the container ref to calculate its boundaries to make my Sticky component working right when initial scrolling offset > 0. Right now I can only receive the container in onScroll handler and to get the container before scrolling is happening, I have to access internal member _container.
Thanks!

**Comment by goldenyz** [comment]
Thanks for the contribution. I have a better way to expose the container ref: [containerRef](https://github.com/goldenyz/react-perfect-scrollbar#containerref). See #23 for more details.
