### ISSUE TITLE
wheel Propagation

### ISSUE THREAD

**Issue by webdevfrancisco** [goldenyz/react-perfect-scrollbar#50]
My understanding is that wheel propagation stops double scrolling on touch devices when set to true.  is there a way to implement this on the react version? thanks.

**Comment by goldenyz** [comment]
> My understanding is that wheel propagation stops double scrolling on touch devices when set to true. is there a way to implement this on the react version? thanks.

You can use this following code:
```
<PerfectScrollbar 
  option={{
    wheelPropagation: true
  }}
>
  ... SCROLLBAR CONTENT HERE ...
</PerfectScrollbar>
```
