### ISSUE TITLE
minScrollbarLength, maxScrollbarLength 

### ISSUE THREAD

**Issue by StarNeit** [goldenyz/react-perfect-scrollbar#55]
Would you please let me know how can use **"minScrollbarLength"** and **"maxScrollbarLength"** like original perfect scrollbar? 
(https://github.com/utatti/perfect-scrollbar)

This react version perfect scrollbar looks good, but I can not find how to use "maxScrollbarLength" in this component. Any idea?

Thank you.

**Comment by goldenyz** [comment]
```jsx
<PerfectScrollbar option={{minScrollbarLength: 20}}>
        ... SCROLLBAR CONTENT HERE ...
</PerfectScrollbar>
```

**Comment by StarNeit** [comment]
Thank you a lot, @goldenyz
