### ISSUE TITLE
Catch event click thumb

### ISSUE THREAD

**Issue by e11en** [goldenyz/react-perfect-scrollbar#64]
I need to catch the event that fires when the thumb is clicked, only using the `onScrollY` doesn't work because it fires only when scroll movement is done. I can't find it in the docs so it could not even exist.
I would love to do something like this:

```
<PerfectScrollbar onThumbEnter={this.OnEnter} onThumbLeave={this.OnLeave} />
```

**Comment by goldenyz** [comment]
What do you want to do by hooking the event?

**Comment by e11en** [comment]
I want to add a css class to something else when the thumb is clicked on and remove it when released. Can't do it with `onScrollY` because that fires every time the thumb moves.

**Comment by goldenyz** [comment]
@e11en I think you can catch any event you want on the parent/children of the container, because of the event bubbling
