### ISSUE TITLE
With the trackpad scrolling does not stop at the bottom of the scrollable area it continues infinitely.

### ISSUE THREAD

**Issue by jeffpowrs** [goldenyz/react-perfect-scrollbar#65]
I have implemented react-perfect-scrollbar inside of a modal and I am experiencing a bug I have not been able to fix and seems to be a bug with react-perfect-scrollbar.

**Expected behavior**: When I scroll to the bottom of the content area and all content is in view, the scrolling should stop and I will no longer be able to scroll inside of this area.

**Actual behavior**: When I scroll to the bottom of the content area and all content is in view, I continue to be able to scroll the content. There seems to be no limit to how far I can scroll it seems to go on infinitely as I watch the content scroll further and further out of view.

If there is anything I can do on my end to resolve this issue please let me know.

**Comment by goldenyz** [comment]
Could you repro it on codesandbox.io to help me find out what happens?

**Comment by frontendmonster** [comment]
Have same issue for horizontal scroll.

**Comment by frontendmonster** [comment]
It happen on `rtl` direction
[Sandbox](https://codesandbox.io/s/perfectscrollbarrtlissue-skq03)

**Comment by kishan143-jaiswal** [comment]
facing same issue

**Comment by goldenyz** [comment]
> It happen on `rtl` direction
> [Sandbox](https://codesandbox.io/s/perfectscrollbarrtlissue-skq03)

fix by v1.5.4
