### ISSUE TITLE
Rename "option" prop to "options"

### ISSUE THREAD

**Issue by G-Rath** [goldenyz/react-perfect-scrollbar#67]
The `option` prop should be `options`, since its a collection of options.

You can prevent this from being a breaking change with the following:

`this._ps = new PerfectScrollbar(this._container, this.props.options || this.props.option);`

I'm happy to make a PR for this, if you're happy for this change to take place.

**Comment by goldenyz** [comment]
@G-Rath Fine. Go ahead to make the change. Pls make a change for readme, too. :-)

**Comment by G-Rath** [comment]
Sweet. I'll make the PR now - Could you approve & merge #68 first for me, as otherwise they'll cause a merge conflict :joy:
