### ISSUE TITLE
v1.5.0 missing merge commit

### ISSUE THREAD

**Issue by chro-codes** [goldenyz/react-perfect-scrollbar#71]
Hey,

according to the changelog v1.5.0 is supposed to contain the merge of #69:
https://github.com/goldenyz/react-perfect-scrollbar/releases/tag/v1.5.0
However, the commit is not included and v1.5.0 is an empty version:
https://github.com/goldenyz/react-perfect-scrollbar/compare/v1.4.4...v1.5.0

You should push a new release including bebee8e

**Comment by goldenyz** [comment]
fixed
