### ISSUE TITLE
no element is specified to initialize PerfectScrollbar

### ISSUE THREAD

**Issue by Trancedified** [goldenyz/react-perfect-scrollbar#72]
Hello,

We're using Jest and Enzyme to do unit tests that includes components with react-perfect-scrollbar. When doing a snapshot test, we got this error: "no element is specified to initialize PerfectScrollbar". The code works fine on the website, just only in the unit test snapshot, we get an error. Any ideas on how to fix this? Thanks!

Here's a code snippet:

`import React from 'react';
import renderer from 'react-test-renderer';
import AbstractHistory from '../src/components/Abstract/AbstractHistory';
import configureStore from 'redux-mock-store';

import expect from 'expect';
import { mount } from 'enzyme';

import { initialState } from '../src/redux/initial-state'
import { Modal } from 'reactstrap';
import PerfectScrollbar from 'react-perfect-scrollbar'
import '../../css/perfect-scrollbar.css'

describe('AbstractHistory (Snapshot)', () => {

    const mockStore = configureStore()
    let store

    beforeEach(() => {
        store = mockStore(initialState)
    })

    it('AbstractHistory snapshot renders', () => {        
        const component = renderer.create(<AbstractHistory store={store} />);
        const json = component.toJSON();
        expect(json).toMatchSnapshot();
    });

});`

**Comment by goldenyz** [comment]
The react-perfect-scrollbar uses refs, so you may need to reference https://reactjs.org/docs/test-renderer.html#ideas to create a mocked ref.

**Comment by Trancedified** [comment]
Thanks for the reply, @goldenyz. I see from the example that createNodeMock is mocking a focus function. Which function should I mock for react-perfect-scrollbar?

**Comment by goldenyz** [comment]
@Trancedified This is a good question. I have glanced at the source code of [perfect-scrollbar](https://github.com/utatti/perfect-scrollbar), a lot of DOM related method has been called. [jsdom](https://github.com/jsdom/jsdom) may give some help with jest

**Comment by BLouzada** [comment]
@Trancedified did you solved this problem?

**Comment by Trancedified** [comment]
> @Trancedified did you solved this problem?

No, we just disabled the unit test.
