### ISSUE TITLE
How do you add "scroll-behavior: smooth;" for cases like scrollTop = 0 ?

### ISSUE THREAD

**Issue by sdevil7th** [goldenyz/react-perfect-scrollbar#75]
I have a big component inside the scrolling wrapper and I have an external trigger for scroll to top. But when it's triggered it scrolls to top in an instant.
I'd like to use the css property "scroll-behavior: smooth;" here so that the transition is smooth.
Please help me on the approach.

**Comment by sdevil7th** [comment]
It can be added to the container and it'll work for the trigger, but then normal scroll triggered by used is not working!

**Comment by goldenyz** [comment]
It would be better if ask this questions to https://github.com/mdbootstrap/perfect-scrollbar. Because this component is just a wrapper for that component
