### ISSUE TITLE
how can i scroll to bottom using ref.scrollTop

### ISSUE THREAD

**Issue by FreshWebCoder** [goldenyz/react-perfect-scrollbar#76]
I have a chat UI inside the scrolling wrapper and scrollbar position is at the top at first.
I'd like to scroll it to the bottom using ref.scrollTop.
how can i get the maximum value of scrollTop?
or Is there any other way to scroll to the bottom?

**Comment by goldenyz** [comment]
try `ref.scrollTop = ref.scrollHeight;`?

**Comment by FreshWebCoder** [comment]
I already tried that way before, but there was an issue.

Value of `onYReachEnd={container => console.log(`scrolled to: ${container.scrollTop}.`)}` and `ref.scrollHeight` were not same.

No way to get proper maximum `ref.scrollTop` value?

**Comment by goldenyz** [comment]
Maybe you should minus the clientHeight

**Comment by IbrahimCanKALYA** [comment]
Hi, i'am troublishing with the same , @FreshWebCoder did you find any solution for this issue?

If you find cloud you share it ?

Thanks in advence.

**Comment by lean1024** [comment]
just try to highest possible number 
this.scrollbarRef.scrollTop = Number.MAX_SAFE_INTEGER

This way it scrolls to the bottom. For example the lowest point of my itemlist with 20 item's is 1166. ( the deeper it scrolls the higher the number of scrollTop becomes. ) By scrolling to the highest number you get to the lowest part of the list.
![image](https://user-images.githubusercontent.com/32680721/60886313-ecc69a00-a251-11e9-914c-fe1739659175.png)

**Comment by IbrahimCanKALYA** [comment]
@lean1024 it's works thanks.

**Comment by lean1024** [comment]
@FreshWebCoder see my previous comment :) if you still need to know how to scroll to the bottom of the list

**Comment by goldenyz** [comment]
Close the issue for @lean1024 resolution

**Comment by feiraelectronica** [comment]
hi @goldenyz , can i see the code? looking for the same solution

**Comment by feiraelectronica** [comment]
> I have a chat UI inside the scrolling wrapper and scrollbar position is at the top at first.
> I'd like to scroll it to the bottom using ref.scrollTop.
> how can i get the maximum value of scrollTop?
> or Is there any other way to scroll to the bottom?

Hi @FreshWebCoder @lean1024 , you found the solution? can you share me the code? need it

**Comment by lean1024** [comment]
1: the solution was presented in this thread. Read more carefully?
2: as far as i remember it was "just try the* highest possible number
this.scrollbarRef.scrollTop = Number.MAX_SAFE_INTEGER" for this threads problem
3: here is the link to my comment https://github.com/goldenyz/react-perfect-scrollbar/issues/76#issuecomment-509614075

@feiraelectronica

**Comment by feiraelectronica** [comment]
> 1: the solution was presented in this thread. Read more carefully?
> 2: as far as i remember it was "just try the* highest possible number
> this.scrollbarRef.scrollTop = Number.MAX_SAFE_INTEGER" for this threads problem
> 3: here is the link to my comment [#76 (comment)](https://github.com/goldenyz/react-perfect-scrollbar/issues/76#issuecomment-509614075)
> 
> @feiraelectronica

i know but where to put the code. is it here?

render() {
    return (
          <PerfectScrollbar  ref={(ref) => { this.scrollbarRef.scrollTop = Number.MAX_SAFE_INTEGER }}>
....
)}

**Comment by lean1024** [comment]
I can only guess, that you are somewhat newish. No offence. 
Shouldnt the ref within <Komponent ref= > point to a ref variable. 
https://reactjs.org/docs/refs-and-the-dom.html
![image](https://user-images.githubusercontent.com/32680721/131974726-ef48a9f6-7b82-4ff0-bc34-b69436e29ef8.png)

As far as i can gues the flow should be:
1. You want to "happen" smth on a "event". Lets say click on a button 
<Button onClick="this.onClick">

while in the function definition 
onClick() {
// you can refer the ref variable 
this.ref.scrollTop = Number.MAX_SAFE_INTEGER
}

smth like here
![image](https://user-images.githubusercontent.com/32680721/131975195-02f6820d-a7b8-4c85-aca3-711b2ff7a00d.png)

is that helpful?

**Comment by phil-dileo** [comment]
I was able to get this to work by stuffing an empty span at the bottom of the list of items and then scrolling to it. 

```import React, { useLayoutEffect, useRef } from 'react';
import Scrollbar from 'react-perfect-scrollbar';

...

const MyComp: FunctionComponent = () => {
  const scrollRef = useRef<HTMLSpanElement>();
  
  useLayoutEffect(() => {
    if (scrollRef?.current) {
      scrollRef.current.scrollIntoView();
    }
  });
  
  return (
    <Scrollbar>
      {_.map(data, (d) => renderItem(d))}
      <span ref={scrollRef} />
    </Scrollbar>
  );
 }```
