### ISSUE TITLE
Two vertical scrolls

### ISSUE THREAD

**Issue by maxshev** [goldenyz/react-perfect-scrollbar#80]
I have 2 blocks, one(small-children) inside second(big-parent), both have 2 vertical scrolls. When small scroll end, big window start scrolling (all this time mouse inside small block). On default scroll it works good: when scrolling stop in small window, big windows doesn't continue scroll. 

i try to fix it by using :hover, but it doesn't help.

**Comment by goldenyz** [comment]
Could you repro it on certain example or [codesandbox.io](https://codesandbox.io/) to help me find out what happens?

**Comment by goldenyz** [comment]
I will close this issue for no any updates.
