### ISSUE TITLE
Not scrolling on touch screens in Chrome

### ISSUE THREAD

**Issue by imsam67** [goldenyz/react-perfect-scrollbar#81]
On Chrome, scroll is not properly responding to touch on touchscreens. It seems to scroll a tiny bit every time I gesture to scroll up or down but it's not an acceptable behavior.

It seems to work OK in Edge but even there, it's very very jumpy but at least it does scroll.

And it's the same issue on the new Chrome based Edge.

Using a mouse, everything works fine but touch produces a very poor experience.

**Comment by goldenyz** [comment]
@imsam67 update the version to v1.5.4 and try again?

**Comment by imsam67** [comment]
Do I need to install the `perfect-scrollbar` package first or does `react-perfect-scrollbar` contain all that's necessary?

**Comment by imsam67** [comment]
I'm not able to get it to work. I also installed the regular `perfect-scrollbar` and initialized it using their instructions and it seems to work. I would love to use this `react-perfect-scrollbar` package but not sure why it's not working.

**Comment by goldenyz** [comment]
@imsam67 `react-perfect-scrollbar` contains all the necessary. Could you repro it on certain example project or [codesandbox.io](https://codesandbox.io) to help me find out what happens?

**Comment by imsam67** [comment]
I was kind of got it working but here's the problem I'm having: I have several sections where I want to use `react-perfect-scrollbar` and be able to create scrolling individually. One of these sections happens to be in an overlay the user can open and close -- like a collapsable panel.

The problem is that only the first section where I used `<PerfectScrollbar>` is working properly. The other sections are not scrolling at all.

Can I only use a single instance of `<PerfectScrollbar>`?

**Comment by goldenyz** [comment]
close this issue for we have another for tracking. #92
