### ISSUE TITLE
Setting wheelPropagation to false not working on mobile devices

### ISSUE THREAD

**Issue by jctiradopatientnow** [goldenyz/react-perfect-scrollbar#82]
Hi,

I want to disable the wheelPropagation the following way...

<PerfectScrollbar option={{ suppressScrollX: true, wheelPropagation: false }}>

This is working ok in computers but working wrong in mobile devices.

Version used: react-perfect-scrollbar@1.5.0

**Comment by goldenyz** [comment]
@jctiradopatientnow update version to 1.5.4 and try again?

**Comment by goldenyz** [comment]
Closed for no updates
