### ISSUE TITLE
onYReachEnd function call on initial render

### ISSUE THREAD

**Issue by raviparmar57** [goldenyz/react-perfect-scrollbar#83]
I am using onYReachEnd function for infinite scroll but function calls on initially render so got error of Maximum update depth exceeded.

version 1.5.3

> <PerfectScrollbar
                    ref={ref => {
                      this._scrollBarRef1 = ref;
                    }}
                    onYReachEnd={container => this.loadMoreItems(container)}
                    options={{ suppressScrollX: true, wheelPropagation: true, }}
                  >
                    {data.length > 0 && (
                      data.map((chat, index) => {
                        return (
                          <ChatListItem
                            key={`chat_${index}`}
                            item={chat}
                          />
                        );
                      })
                    )}
                  </PerfectScrollbar>
![2019-09-23 18_56_39-Window](https://user-images.githubusercontent.com/45329100/65429502-e8af1f00-de33-11e9-8d4a-ec1c4d452c65.png)

**Comment by kishan143-jaiswal** [comment]
> I am using onYReachEnd function for infinite scroll but function calls on initially render so got error of Maximum update depth exceeded.
> 
> version 1.5.3
> 
> > <PerfectScrollbar
> > ref={ref => {
> > this._scrollBarRef1 = ref;
> > }}
> > onYReachEnd={container => this.loadMoreItems(container)}
> > options={{ suppressScrollX: true, wheelPropagation: true, }}
> > >
> > {data.length > 0 && (
> > data.map((chat, index) => {
> > return (
> > <ChatListItem
> > key={`chat_${index}`}
> > item={chat}
> > />
> > );
> > })
> > )}
> > 
> > ![2019-09-23 18_56_39-Window](https://user-images.githubusercontent.com/45329100/65429502-e8af1f00-de33-11e9-8d4a-ec1c4d452c65.png)

facing same problem while infinity scroll

**Comment by goldenyz** [comment]
@raviparmar57 Could you repro it on certain example project or codesandbox.io to help me find out what happens?

**Comment by goldenyz** [comment]
Closed for no updates.

**Comment by Justicism15** [comment]
Hello, I'm also experiencing this one on Perfect Scrollbar.   
  <PerfectScrollbar
            className="test"
            onYReachStart={(container) => this.handlePagination()}
  >

I also get the same error.

**Comment by goldenyz** [comment]
@Justicism15  Could you repro it on certain example project or codesandbox.io to help me find out what happens?

**Comment by pin1128** [comment]
Hello, I am also getting same error
https://codesandbox.io/s/competent-fermi-jnpl0?file=/src/App.js

**Comment by pin1128** [comment]
> @Justicism15 Could you repro it on certain example project or codesandbox.io to help me find out what happens?

I've made an example; https://codesandbox.io/s/competent-fermi-jnpl0?file=/src/App.js

**Comment by jdev422** [comment]
> @Justicism15 Could you repro it on certain example project or codesandbox.io to help me find out what happens?

https://codesandbox.io/s/competent-fermi-jnpl0?file=/src/App.js
here is an example

**Comment by wallace-sf** [comment]
@goldenyz Any update on this?

**Comment by ValeriyDyachenko** [comment]
The initial loading behavior with `onYReachEnd` is inconsistent and confusing. It works intermittently, and occasionally, it triggers numerous callback calls.

Although I don't have a sandbox to demonstrate the issue with the spam calls, I have created a reproduction scenario where the initial loading either works or fails: https://codesandbox.io/p/sandbox/zealous-kirch-zknwd6?file=%2Fsrc%2FApp.js. If you remove useEffect, the initial loading stops working. Do you have any insights into why this occurs? Could it be related to the issue with the spam calls?

```js
import React, { useState, useEffect } from "react";
import { debounce } from "lodash";
import "./styles.css";
import PerfectScrollbar from "react-perfect-scrollbar";
import "react-perfect-scrollbar/dist/css/styles.css";

const arr = [1];
const App = () => {
  const [items, setItems] = useState(arr);
  const handlePagination = () => {
    console.log("=============");
    setItems([...items, ...arr]);
  };

  // remove this useEffect, and preloading will be broken, why it's happens?
  useEffect(() => {
    handlePagination();
  }, []);

  return (
    <div
      style={{
        border: "1px solid black",
        height: "200px",
        overflow: "auto",
      }}
    >
      <PerfectScrollbar onYReachEnd={debounce(handlePagination, 100)}>
        {items.map((_, i) => (
          <h2 key={i}>Start editing to see some magic happen {i}</h2>
        ))}
      </PerfectScrollbar>
    </div>
  );
};

export default App;
```
