### ISSUE TITLE
containerRef is not working

### ISSUE THREAD

**Issue by hogenishi** [goldenyz/react-perfect-scrollbar#84]
```
this._scrollRef.scrollTop = 0;
```
If the code is readme, it will not work.

```
this._scrollRef._container.scrollTop = 0;
```
It works if you replace the code as above.

**Comment by ecfy** [comment]
+1 - Same issue here

**Comment by goldenyz** [comment]
Use the containerRef to set the property. Refer to https://github.com/goldenyz/react-perfect-scrollbar#containerref for more details
