### ISSUE TITLE
CSS: Transparent Rail

### ISSUE THREAD

**Issue by jlllo** [goldenyz/react-perfect-scrollbar#85]
I couldn't place the transparent rail unless I applied the style to the overall application styles. Anyway, this way it worked for me.

![global-styles](https://user-images.githubusercontent.com/50778558/68522444-1cca8c00-028a-11ea-8ce1-1909249cdcdb.png)
![preview](https://user-images.githubusercontent.com/50778558/68522446-1e944f80-028a-11ea-90e8-096ce08600fd.png)

**Comment by goldenyz** [comment]
It is by design.
