### ISSUE TITLE
Scrollbar goes crazy 

### ISSUE THREAD

**Issue by goxr3plus** [goldenyz/react-perfect-scrollbar#86]
![2019-12-18_16-07-18](https://user-images.githubusercontent.com/20374208/71092851-b69e2680-21b0-11ea-9bcb-6902df05fabd.gif)

This happens when the scrollbar is about to be shown , and it's unstopable , what's wrong :(

**Comment by goxr3plus** [comment]
In the gif is not visible good enough but it flickers all the time . What maybe causes that ?

**Comment by goldenyz** [comment]
Could you repro it on certain example project or codesandbox.io to help me find out what happens?

**Comment by goldenyz** [comment]
@goxr3plus  Any updates?

**Comment by goxr3plus** [comment]
Well i couldn't reproduce because i removed yhe library but that gif shows it :)

**Comment by goldenyz** [comment]
But what can I do if it cannot be repro?

**Comment by goxr3plus** [comment]
I am gonna close this issue :)
