### ISSUE TITLE
the perf issue in the scenario that children nodes change frequently

### ISSUE THREAD

**Issue by haoliangwu** [goldenyz/react-perfect-scrollbar#87]
I believe the root cause is due to https://github.com/goldenyz/react-perfect-scrollbar/blob/f3bd7a87771627bad6507e413412df18893e95d3/src/scrollbar.js#L39.

the following is the perf screenshot of my company current project:
![image](https://user-images.githubusercontent.com/6328186/71441952-b072f180-273e-11ea-98ef-d5af553330d8.png)

the business is related to real-time trading, so the children of order book component change frequently and I found this library always call `this._ps.update()` after its children changed. This will cause the whole page to recalculate style frequently and decrease the FPS.

Is there a better way to solve this? IMHO, the `ps.update()` is used to sync scroll container when the size or content of scroll container change, but maybe it is a little overwhelming to trigger it in each CDU lifecycle.

is it better to expose `prop` to indicate the meaning of bypassing this logic when we know our scroll container is fixed or just debounce it?

**Comment by haoliangwu** [comment]
I apply fixed prop into the fork version of this repo and using it to bypass the sync logic, the perf screenshot is following:
![image](https://user-images.githubusercontent.com/6328186/71407320-ae912b80-2675-11ea-96b0-d861079fb100.png)

**Comment by goldenyz** [comment]
@haoliangwu Thanks for reporting this issue. The reason to call `ps.update()` in `componentDidUpdate` is that in most cases, people change the children when using this component. You can make a HOC `ScrollbarWrapper` which wraps the `PerfectScrollbar` and extends the `PureComponent` to prevent from unexpected update. But you may need to call [updateScroll](https://github.com/goldenyz/react-perfect-scrollbar#updatescroll) if children changes. 
If you do want this `ps.update()` logic with better performance, the debounce logic is really a good idea. Could you help to create a PR for it?

**Comment by haoliangwu** [comment]
@goldenyz 

please do code review at #91 when you have free time. thx.
