### ISSUE TITLE
Max-height works differently than vanilla perfect-scrollbar

### ISSUE THREAD

**Issue by handeyeco** [goldenyz/react-perfect-scrollbar#88]
Hello and thank you for maintaining this project.

I have two examples to illustrate the issue I'm running into:

* [Vanilla Perfect Scrollbar](https://codesandbox.io/s/ps-max-height-expected-1yi35)
* [React Perfect Scrollbar](https://codesandbox.io/s/ps-max-height-actual-7vidw)

In both demos I have four examples:

1. Container has a **height** of 15rem with <15rem worth of content. In both there is whitespace below content (this is what I'm ultimately trying to avoid).
2. Container has a **height** of 15rem with >15rem worth of content. Both examples work as expected.
3. Container has a **max-height** of 15rem with <15rem worth of content. In both the container shrinks to the size of the content (this is the ideal).
4. Container has a **max-height** of 15rem with >15rem worth of content. With `perfect-scrollbar` the result is identical to using height; with `react-perfect-scrollbar` scrolling is disabled.

Again, thank you for taking the time to look at this. If there are additional details or examples I could provide, please let me know.

**Comment by handeyeco** [comment]
In the `perfect-scrollbar` example I mention another bug I filed. I think it's unrelated, but interestingly it doesn't happen with `react-perfect-scrollbar`. This may be a red flag that I don't know what I'm doing. 😉 Just in case it's relevant: https://github.com/mdbootstrap/perfect-scrollbar/issues/899

**Comment by goldenyz** [comment]
The identical implementation for:
```html
    <div class="select">
      <div class="select__head">Select</div>
      <div class="select__dropdown">
        <div class="select__ps select__ps--height" id="select__ps1">
          <div class="select__option">Option</div>
          <div class="select__option">Option</div>
        </div>
      </div>
    </div>
```
would be
```jsx
    <div className="select">
      <div className="select__head">Select</div>
      <div className="select__dropdown">
        <PerfectScrollbar className="select__ps select__ps--height">
          <div className="select__option">Option</div>
          <div className="select__option">Option</div>
        </PerfectScrollbar>
      </div>
    </div>
```

**Comment by handeyeco** [comment]
Ah, obviously I misunderstood what was going on. Thank you for looking into this!
