### ISSUE TITLE
How can I suppress scroll?

### ISSUE THREAD

**Issue by nickmask** [goldenyz/react-perfect-scrollbar#95]
On the original perfect-scroll bar there is an option to `suppressScrollY` or `suppressScrollX`. Is there any way to achieve this with react-perfect-scrollbar?

**Comment by DrFlink** [comment]
You can access the original props through the[ `options` prop](https://github.com/goldenyz/react-perfect-scrollbar#options).

`<PerfectScrollbar options={{ supressScrollY: true }}><...</PerfectScroll>`

**Comment by claezon** [comment]
> On the original perfect-scroll bar there is an option to `suppressScrollY` or `suppressScrollX`. Is there any way to achieve this with react-perfect-scrollbar?

You can access the original props through the[ `options` prop](https://github.com/goldenyz/react-perfect-scrollbar#options).

`<PerfectScrollbar options={{ supressScrollY: true }}>...</PerfectScroll>`
