### ISSUE TITLE
How to use containerRef?

### ISSUE THREAD

**Issue by danielcai1987** [goldenyz/react-perfect-scrollbar#96]
Dear Allen,

Thank you for making this react wrapper for perfect-scrollbar.
I'm trying to use it in my project.
Do you have an example with more details of how to use the containerRef?
I was trying to scroll down in the container area when there is a button clicked.

Thank you very much!
Daniel

**Comment by goldenyz** [comment]
```jsx
<PerfectScrollbar
  containerRef={(ref) => {this._scrollRef = ref;}}
>
  ...
</PerfectScrollbar>
```

then do what you want for a regular `div`, like:
```js
// change scroll top
this._scrollRef.scrollTop = 0;

// change scroll left
this._scrollRef.scrollLeft = 0;
```

**Comment by danielcai1987** [comment]
Thank you for the prompt reply, it works perfect!
But I put it in an async funtion to work, because the container height will increase when there is a new row.

```
setTimeout(() => {
      this._scrollRef.scrollTop = 50*(rows.length)
}, 0);
```
