### ISSUE TITLE
Warning: Unknown event handler property `onUpdateSize`. It will be ignored.

### ISSUE THREAD

**Issue by kishan143-jaiswal** [goldenyz/react-perfect-scrollbar#97]
getting this warning in console , is any prop name is updated in the library

**Comment by goldenyz** [comment]
It seems you attached a onUpdateSize to this component which doesn't support

**Comment by kishan143-jaiswal** [comment]
previous version :1.5.3 i m not getting this warning while using this function as prop

**Comment by goldenyz** [comment]
Because we will attach the remaining props which doesn't list in README to the inner root container DOM element

**Comment by goldenyz** [comment]
I will close this issue for it is a by design behavior
